version: '3.9'

services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    networks:
      - my-network

  web:
    build: .
    stop_signal: SIGINT
    ports:
      - '4000:80'
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
